import type { Track } from "../../types/track.ts";

export const tracks = [
  {
    id: "ember_after_midnight",
    title: "Ember After Midnight",
    artist: "Mara Vale",
    album: "Low Light Letters",
    coverUrl: "/assets/covers/ember_after_midnight-pattern-v2.png",
    previewAudioUrl: "/assets/audio/ember_after_midnight.wav",
    previewDurationSeconds: 6,
    lyricsExcerpt: "Leave the lamp low, let the quiet say my name.",
    tags: {
      genres: ["Neo Soul", "Quiet Storm"],
      moods: ["Intimate", "Late Night"],
      voices: ["Velvet Alto", "Close Mic"],
      production: ["Rhodes", "Tape Warmth"],
    },
    listeningNote:
      "像壁炉将熄未熄时的余温，嗓音贴得很近，Rhodes 只留下必要的光。",
  },
  {
    id: "satin_window",
    title: "Satin Window",
    artist: "Mara Vale",
    album: "Low Light Letters",
    coverUrl: "/assets/covers/satin_window-pattern-v2.png",
    previewAudioUrl: "/assets/audio/satin_window.wav",
    previewDurationSeconds: 6,
    lyricsExcerpt: "Your shadow moves softly through the satin window.",
    tags: {
      genres: ["Neo Soul", "Slow Jam"],
      moods: ["Tender", "Nocturnal"],
      voices: ["Velvet Alto", "Breathy"],
      production: ["Electric Piano", "Brushed Drums"],
    },
    listeningNote:
      "同一副柔软嗓音换成更轻的鼓刷，像夜风从半开的窗帘后缓慢经过。",
  },
  {
    id: "slow_bloom",
    title: "Slow Bloom",
    artist: "Elias Rowe",
    album: "Rooms in Amber",
    coverUrl: "/assets/covers/slow_bloom-pattern-v2.png",
    previewAudioUrl: "/assets/audio/slow_bloom.wav",
    previewDurationSeconds: 6,
    lyricsExcerpt: "We do not have to hurry what the dark can grow.",
    tags: {
      genres: ["Alternative R&B", "Soul"],
      moods: ["Patient", "Warm"],
      voices: ["Soft Tenor", "Layered Falsetto"],
      production: ["Muted Bass", "Analog Pad"],
    },
    listeningNote:
      "松弛的男声不急着抵达副歌，低频和模拟合成器把时间慢慢拉长。",
  },
  {
    id: "hallway_echo",
    title: "Hallway Echo",
    artist: "Elias Rowe",
    album: "Rooms in Amber",
    coverUrl: "/assets/covers/hallway_echo-pattern-v2.png",
    previewAudioUrl: "/assets/audio/hallway_echo.wav",
    previewDurationSeconds: 6,
    lyricsExcerpt: "One last note is waiting where the hallway bends.",
    tags: {
      genres: ["Alternative R&B", "Quiet Storm"],
      moods: ["Reflective", "After Hours"],
      voices: ["Soft Tenor", "Airy Falsetto"],
      production: ["Room Reverb", "Muted Guitar"],
    },
    listeningNote:
      "尾音被房间混响轻轻拉远，木吉他闷音让孤独听起来并不冰冷。",
  },
  {
    id: "honey_static",
    title: "Honey Static",
    artist: "Nia Sol",
    album: "Golden Frequency",
    coverUrl: "/assets/covers/honey_static-pattern-v2.png",
    previewAudioUrl: "/assets/audio/honey_static.wav",
    previewDurationSeconds: 6,
    lyricsExcerpt: "Your voice is honey static humming under my skin.",
    tags: {
      genres: ["Contemporary R&B", "Neo Soul"],
      moods: ["Magnetic", "Mellow"],
      voices: ["Smoky Mezzo", "Rounded"],
      production: ["Vinyl Noise", "Sub Bass"],
    },
    listeningNote:
      "沙哑中音和细微唱片底噪黏在一起，低频饱满，却始终没有挤压空间。",
  },
  {
    id: "velvet_receiver",
    title: "Velvet Receiver",
    artist: "Nia Sol",
    album: "Golden Frequency",
    coverUrl: "/assets/covers/velvet_receiver-pattern-v2.png",
    previewAudioUrl: "/assets/audio/velvet_receiver.wav",
    previewDurationSeconds: 6,
    lyricsExcerpt: "Call me through the velvet, I will hear the quiet part.",
    tags: {
      genres: ["Contemporary R&B", "Slow Jam"],
      moods: ["Romantic", "Dimly Lit"],
      voices: ["Smoky Mezzo", "Close Mic"],
      production: ["Wurlitzer", "Soft Claps"],
    },
    listeningNote:
      "Wurlitzer 的暖亮边缘托住近距离人声，像旧电话里只说给一个人听的话。",
  },
  {
    id: "blue_hour_vinyl",
    title: "Blue Hour Vinyl",
    artist: "Theo June",
    album: "Soft Corners",
    coverUrl: "/assets/covers/blue_hour_vinyl-pattern-v2.png",
    previewAudioUrl: "/assets/audio/blue_hour_vinyl.wav",
    previewDurationSeconds: 6,
    lyricsExcerpt: "Turn the blue hour over, let the other side begin.",
    tags: {
      genres: ["Soul", "Lo-Fi R&B"],
      moods: ["Nostalgic", "Unhurried"],
      voices: ["Grainy Baritone", "Low Register"],
      production: ["Tape Flutter", "Dusty Drums"],
    },
    listeningNote:
      "颗粒感男中音压在拍点后面，磁带晃动和旧鼓机让整首歌像被时间磨过。",
  },
  {
    id: "quiet_side_of_rain",
    title: "Quiet Side of Rain",
    artist: "Theo June",
    album: "Soft Corners",
    coverUrl: "/assets/covers/quiet_side_of_rain-pattern-v2.png",
    previewAudioUrl: "/assets/audio/quiet_side_of_rain.wav",
    previewDurationSeconds: 6,
    lyricsExcerpt: "Meet me on the quiet side of rain before it clears.",
    tags: {
      genres: ["Soul", "Quiet Storm"],
      moods: ["Rainy", "Reassuring"],
      voices: ["Grainy Baritone", "Gentle"],
      production: ["Jazz Guitar", "Brush Kit"],
    },
    listeningNote:
      "爵士吉他和刷鼓把雨夜留出缝隙，低沉嗓音听起来稳妥而不沉重。",
  },
  {
    id: "velvet_weather",
    title: "Velvet Weather",
    artist: "Amara Grey",
    album: "Between the Lamps",
    coverUrl: "/assets/covers/velvet_weather-pattern-v2.png",
    previewAudioUrl: "/assets/audio/velvet_weather.wav",
    previewDurationSeconds: 6,
    lyricsExcerpt: "Stay until the velvet weather settles in the room.",
    tags: {
      genres: ["Neo Soul", "Jazz R&B"],
      moods: ["Sophisticated", "Calm"],
      voices: ["Clear Contralto", "Silky"],
      production: ["Upright Bass", "Warm Horns"],
    },
    listeningNote:
      "清晰女低音从立式贝斯上方滑过，铜管只在句尾出现，成熟而克制。",
  },
  {
    id: "candle_smoke",
    title: "Candle Smoke",
    artist: "Amara Grey",
    album: "Between the Lamps",
    coverUrl: "/assets/covers/candle_smoke-pattern-v2.png",
    previewAudioUrl: "/assets/audio/candle_smoke.wav",
    previewDurationSeconds: 6,
    lyricsExcerpt: "Candle smoke is writing every word we never used.",
    tags: {
      genres: ["Jazz R&B", "Quiet Storm"],
      moods: ["Introspective", "Smoldering"],
      voices: ["Clear Contralto", "Restrained"],
      production: ["Felt Piano", "Ribbon Mic"],
    },
    listeningNote:
      "毛毡钢琴削去了尖锐轮廓，女低音用很少的力气留下长久的余味。",
  },
] satisfies readonly Track[];
